### ISSUE TITLE
Vector Arithmetic Library

### ISSUE THREAD

**Issue by RadeKornjaca** [DaniloNovakovic/git_gud_REPL#2]
Make a new small library for vector arithmetic operations, which will contain at least:
- a function for scalar product
- a function for vector product

You may add some other vector operations if you wish. This should be enough for start.

The library's header and source file should be in projects root directory (preferably called vector_arithmetic.h and vector_arithmetic.c).

**Comment by DaniloNovakovic** [comment]
https://www.youtube.com/watch?v=5r06heQ5HsI
